# Generated by Django 5.1.4 on 2025-11-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="BLogPost",
        ),
    ]
